### ISSUE TITLE
Formatting a .res file will put extra quotes around Element titles which already have quotes

### ISSUE THREAD

**Issue by XcapeEst** [cooolbros/vscode-vdf#1]
![image](https://user-images.githubusercontent.com/27555338/152234812-7deeeb35-5fac-4116-b651-964f4e6b94ee.png)
![image](https://user-images.githubusercontent.com/27555338/152234844-db2abf7b-b2bb-4065-b16b-4c671a7fbc56.png)

**Comment by cooolbros** [comment]
Hi, thanks for reporting this issue.

This issue has been fixed in 5a78251c3cff54492573e4cacbb7505bc8af6985 and the fix has been included in release 2.1.0
