### ISSUE TITLE
Support for `mod_textures.txt`

### ISSUE THREAD

**Issue by qkeitoe** [cooolbros/vscode-vdf#11]
It seems that `mod_textures.txt` matches VDF so it would be helpful if the extension could support this file and related ones as well.

**Comment by cooolbros** [comment]
I've added `mod_textures.txt` to the `filenames` list so it gets syntax highlighting, formatting etc. Some links might not work properly though, if this becomes problem you can create another issue

**Comment by qkeitoe** [comment]
Some huds (such as m0rehud or budhud) uses #base statements to structure `mod_textures`. If possible, I think it would be nice to have an option to name related files in such way that they would also be recognized as VDF, as you did for hudanimations by adding
```
"filenamePatterns": [
    "*hudanimations*.txt"
],
```

**Comment by cooolbros** [comment]
I don't want to add support for specific HUDs' conventions for file naming because it would make HUDs rely on the extension for proper tooling, but this can be achieved in the HUD repository with a `.vscode/settings.json` file resembling the following (which will work for m0rehud):

```json
{
    "files.associations": {
        "textures_*.txt": "vdf"
    }
}
```

**Comment by qkeitoe** [comment]
For some reason I always thought that this setting didn't support such expressions. Thanks!
