### ISSUE TITLE
parse error while extra label [ $someone || $someone ]

### ISSUE THREAD

**Issue by zombie110year** [cooolbros/vscode-vdf#23]
I don't know the name of `[ $someone || $someone ]`, but there was a part of real file in Left 4 Dead 2 UI defination:

```vdf
"Resource/UI/Addons.res"
{
    // because in longer languages the button text overlaps the icon, I'm only making it visible for these languages
    "IconBrowseWorkshop" [$english || $spanish || $finnish || $brazilian || $japanese || $korean || $latam || $portuguese || $schinese || $tchinese || $swedish || $thai || $turkish]
    {
        "ControlName"       "ImagePanel"
        "fieldName"         "IconBrowseWorkshop"
        "xpos"              "c-50" [$win32wide]
        "xpos"              "c-100"
        "ypos"              "440" [$win32wide]
        "ypos"              "455"
        "zpos"              "0"
        "wide"              "30" [$win32wide]
        "tall"              "30" [$win32wide]
        "wide"              "15"
        "tall"              "15"
        "scaleImage"        "1"
        "pinCorner"         "0"
        "visible"           "1"
        "enabled"           "1"
        "tabPosition"       "0"
        "image"             "addonsmenu/icon_browse_workshop"
    }
}
```

It throws an error `Unexpected '{'. Expected key.`

I guess problem occursined by the label `[$english || $spanish || $finnish || $brazilian || $japanese || $korean || $latam || $portuguese || $schinese || $tchinese || $swedish || $thai || $turkish]`.

+ It's Ok: `[$english]`
+ It's Error: `[$english || $spanish]`

### extension version

v4.3.0

**Comment by cooolbros** [comment]
Hi, thanks for reporting this issue

I fixed this in e8f7ce4 and the fix has been included in the latest release (version 4.6.0).

Note that complex conditionals aren't allowed in TF2, which this extension is optimised for, so this behaviour may change in future (possibly a warning or diagnostic)
