### ISSUE TITLE
Auto completion for item attributes when within an ItemAttributes or CharacterAttributes block

### ISSUE THREAD

**Issue by Windolon** [cooolbros/vscode-vdf#32]
I can see that some attributes are supported as screencapped below:
![image](https://github.com/user-attachments/assets/dae7a62e-285f-4be3-bb3d-e93e9411f379)

But it would be great if all of them are supported, mostly just to reduce the compulsion of "let's spend 5 seconds to make sure I copy-pasted this right or I typed this right". Feel free to mark this as impossible or improbable if the attribute list proves to be too long to do anything with.

List can be found here: https://wiki.teamfortress.com/wiki/List_of_item_attributes
Or from items_game.txt found in [TF2 folder]/tf/scripts/items/items_game.txt - lines 209242 to 217147.

**Comment by Windolon** [comment]
Obviously obsecure attributes may be skimmed over and ignored, like attribute id 2000 to 2009 `recipe component defined item`.

**Comment by cooolbros** [comment]
Added in 789fbb3
