### ISSUE TITLE
Formatting code with [$WIN32] causes double quotes

### ISSUE THREAD

**Issue by XcapeEst** [cooolbros/vscode-vdf#7]
![image](https://user-images.githubusercontent.com/27555338/175662819-0c8c97d4-f8fa-4f99-b419-5bdd48e26046.png)
![image](https://user-images.githubusercontent.com/27555338/175662839-126ef1b0-83a9-4beb-92cf-0011ebd2b7d6.png)

**Comment by cooolbros** [comment]
Fix in 3.0.0. Thanks for reporting this issue
